version: '3.1'

services:
  mongo:
    image: mongo
    restart: "no"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MD_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MD_PASSWORD}
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: "no"
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MD_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MD_PASSWORD}
